# Dockerfile.next

# --- Builder Stage ---
FROM node:18-alpine AS builder

WORKDIR /app

COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm install

COPY ./frontend ./
RUN npm run build

# --- Final Stage ---
FROM nginx:1.21.6-alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
